import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NextUiProvider } from "./nextUiProvider";
import I18NextProvider from "./I18NextProvider";
import "swiper/css/navigation";
import "./globals.css";

const montserrat = Montserrat({ subsets: [] });

export const metadata: Metadata = {
	title: "PC Peru",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<I18NextProvider>
					<NextUiProvider>
						<main className="custom-light text-foreground bg-background">
							{children}
						</main>
					</NextUiProvider>
				</I18NextProvider>
			</body>
		</html>
	);
}
